DROP TABLE IF EXISTS BetaVideos;
DROP TABLE IF EXISTS ChallengeVideos;
DROP TABLE IF EXISTS ChallengeStrings;
DROP TABLE IF EXISTS Comments;
DROP TABLE IF EXISTS Climbs;
DROP TABLE IF EXISTS Gyms;
DROP TABLE IF EXISTS Users;
