DROP TABLE IF EXISTS Gym;
DROP TABLE IF EXISTS ClimbsList;
DROP TABLE IF EXISTS Climb;
DROP TABLE IF EXISTS Comments;
DROP TABLE IF EXISTS ChallengeStrings;
DROP TABLE IF EXISTS ChallengeVideos;
DROP TABLE IF EXISTS BetaVideos;
DROP TABLE IF EXISTS Users;
